### PR TITLE
Remove support for VS 2019

### PR DESCRIPTION
**Pull request by ErikEJ**

### CODE REVIEW

**Comment by Ronan-Farrell** [comment]
@ErikEJ , would you have a link to the latest VSIX that supported VS2019? I'm asking because we still need to use 2019 when working with MYSQL databases.

**Comment by ErikEJ** [comment]
@Ronan-Farrell Yes can use MySQL with VS 2022 - just use a custom connection - see the wiki

**Comment by Ronan-Farrell** [comment]
You are absolutely right, my bad - and thank you!

**Comment by mikrob24RUS** [comment]
I reinstalled VS2019 and found that I can't install your extension now. Can you compile and upload the latest VS2019 compatible version?

**Comment by ErikEJ** [comment]
@mikrob24RUS What is preventing you from using VS 2022?

**Comment by ErikEJ** [comment]
@mikrob24RUS Have a look in the Tools folder in this repo

**Comment by mikrob24RUS** [comment]
There are old projects that need support.
Thanks! Solved the issue! File from the directory "tools/VS2019Support/EF Core Power Tools v2.5.1236.vsix.zip" renamed to "tools/VS2019Support/EF Core PowerTools v2.5.1236.vsix", runing the installation and everything was installed! Thanks again!

**Comment by ErikEJ** [comment]
@mikrob24RUS  You are very welcome!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Pull request merged**
