### PR TITLE
always return List<T> from DbContextExtensions

### LINKED ISSUE #986: Always return list from DbContextExtensions

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #986

### CODE REVIEW

**Comment by the-super-coder** [comment]
Hi,
Any discussion on this issue? Why was this breaking change introduced?

**Comment by ErikEJ** [comment]
Because I got it wrong the first time, and so I have less code to maintain.

**Comment by the-super-coder** [comment]
Thanks @ErikEJ . #EfCorePT has really been a very productive tool for me and my team.

So there is no chance of going back? I currently have 6 DBContexts and StoredProcedureContexts and it is going to grow further, so if I regenerate the code for all of those now and retest all apps, do you have think of any reason of reverting it back in future?

**Comment by ErikEJ** [comment]
I will never revert it back, and any future changes will be non-breaking.

**Comment by the-super-coder** [comment]
Awesome! Thanks.

**Pull request merged**
