### PR TITLE
add a global.json

### PR DESCRIPTION
**Pull request by SimonCropp**
so we can ensure a reliable and consistent sdk version

### CODE REVIEW

**Comment by ErikEJ** [comment]
Looks like the pipeline must be updated?

**Comment by ErikEJ** [comment]
How is this different from letting the build agent just use the latest stable?

**Comment by SimonCropp** [comment]
* for me i want to know that local, on CI, and anyone contributing. all are using the latest sdk. so i can rule out any bugs in older sdk as a culprit in diagnosing issues.
 * sometimes perf (and other) bugs are fixed in the compiler (hence sdk). so i want all my projects to be ensured of having these fixes

**Comment by ErikEJ** [comment]
Thanks!

**Pull request merged**
