### PR TITLE
Support localization for Korean

### LINKED ISSUE #2034: [Feature] Add Korean localization
Languages or language updates:

- [x] Korean
- [x] Japanese
- [x] Polish (in progress)
- [x] Russian
- [x] French updates
- [x] Italian updates
- [x] Turkish updates
- [x] Czech
- [x] German
- [x] Zh hant
- [x] Portugese (Brazil)
- [x] Zh Hans updates
- [x] Spanish updates

Guide: 

- Fork and clone the repo
- Open in VS 2022
- Open the /src/GUI/EFCorePowerTools.sln file
- Open the EFCorePowerTools project
- In the Locales folder, copy each *.en.resx file to your language, f.ex. *.de.resx
- Translate the strings in the newly created files (maybe install the extension to understand context)
- In the root folder copy VSpackage.en.resx to your language, f.ex.  VSpackage.de.resx and translate
- In the root folder, copy EFCorePowerToolsPackage.en.vsct to your language, f.ex. EFCorePowerToolsPackage.de.vsct and translate all `<ButtonText>` entries
- Create a Pull Request with your changes!

Any contributor gets 1 hour of free consultancy!

List of [supported languages](https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022#step-6---install-language-packs-optional)

### PR DESCRIPTION
**Pull request by utilForever**
This revision includes:
- Support localization  for Korean (Resolves #2034)

### CODE REVIEW

**Comment by utilForever** [comment]
I have a few sentences left to translate, but I'll finish them in the next few hours.

**Comment by ErikEJ** [comment]
Could you verify against the other two PRs?

**Comment by preco21** [comment]
Hi, @utilForever. We have competing PRs suggesting similar changes. @ErikEJ asked me to if I can incooperate other changes like in this PR.

Would you mind participating in this [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/2403) instead?

This way, we can consolidate our efforts and ensure a unified translation.

However, if you prefer to make a separate contribution, it would be great to have a subsequent PR for further improvements. 

Thank you!

**Comment by utilForever** [comment]
> Hi, @utilForever. We have competing PRs suggesting similar changes. @ErikEJ asked me to if I can incooperate other changes like in this PR.
> 
> Would you mind participating in this [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/2403) instead? (cross-check, review, etc.)
> 
> This way, we can consolidate our efforts and ensure a unified translation.
> 
> However, if you prefer to make a separate contribution, it would be great to have a subsequent PR for further improvements.
> 
> Thank you!

1. I am willing to close this PR and merge it with the linked PR.
2. I have a translation that I would like to change and would like some guidelines on how to proceed.

**Comment by preco21** [comment]
@utilForever Thank you for your response! Could you please submit code review on the linked [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/2403/files), if any?

**Comment by utilForever** [comment]
> @utilForever Thank you for your response! Could you please submit code review on the linked [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/2403/files), if any?

Okay. I closed this PR and will submit code review on the linked PR.

**Pull request closed without merging**
