### PR TITLE
New option to tell the reverse engineering process to create non nullable boolean properties only

### PR DESCRIPTION
**Pull request by StefanFalz**
Added a new option GenerateNonNullableBoolsOnly (located in the AdvancedModelingOptionsDialog) to tell the reverse engineering process to create non nullable boolean properties only, no matter what kind of default value is specified for the bit column in the database.

If this option is set, each not nullable bit column with a sql default value other than 0 is mapped as:

```csharp
public bool IsActive { get; set; }
```

instead of:

```csharp
[Required]
public bool? IsActive { get; set; }
```

If there is no default value or a value of 0 specified, the scaffolder already generates public bool IsActive { get; set; }.

I think, there could a bunch of people which will like this option.

### CODE REVIEW

**Comment by ErikEJ** [comment]
What if you are not using DataAnnotations ?

**Comment by ErikEJ** [comment]
What is it with (SF) in the vsct file,??

**Comment by StefanFalz** [comment]
> 
> 
> What is it with (SF) in the vsct file,??

Sorry, my fault. I thought I'd removed that. It's done and commited now.

>
>
> What if you are not using DataAnnotations ?

In this case I don't see any way to retrieve the information whether the bit column in the database is nullable or not in the ReverseEngineerRunner class.

At the first look I thought the neccessary changes in the project could be made in the CommentCSharpEntityTypeGenerator class but the methods in this class are never executed? The GenerateProperties and GenerateRequiredAttribute would have been great places for the changes.

Ok, one could execute some SQL scripts against the database to check whether the column is nullable or not but I don't think this is the right way.

Do you have a suggestion how this could be solved?

---

It's ok if you decline the pull request. I'm new to Git and perhaps I accidentally didn't follow some rules. But I promise I am working on it. :)

**Comment by ErikEJ** [comment]
Sorry, but I am not going to accept this - see the explanation here: https://github.com/dotnet/efcore/issues/10840#issuecomment-362047565 - so the correct resolution if you must have non-nullable properties is to drop the constraint.

Maybe it is a good idea to discsuss a PR before spending time on the actual code?

**Comment by StefanFalz** [comment]
>
> 
> Maybe it is a good idea to discsuss a PR before spending time on the actual code?

Your are right. But in my case the spended time wasn't wasted. I can use the adapted version in my local environment for now and that's ok for me. To avoid problems with future versions of your tools, I'll outsource the changes into a separate project.

I understand the explanation from @bricelam but our devs see it the same way I do.

Thank you for your time and again for your excellent extension.

**Comment by ErikEJ** [comment]
@StefanFalz Fine, but I do not understand how you will then need the database default.

If you use a non nullable property, EF Core will always set the value to 0 unless you explicitly set it to 1,  and if you do that, the database default makes no sense !?

**Comment by rationalmonkey** [comment]
ErikEJ, why are you viewing it like Entity Framework is what those database constraints are there for in the first place.  Our project just tried to convert our primary database to EF Core (instead of EF6) and this single issue is the final issue that prevented it.  Our 2 newer databases already use EF Core and we were trying to finally end-of-life EF6.  We simply cannot make these columns nullable in C# (that's not our business layer's intention) and we cannot remove the default constraints (those are used by our seed data pipeline, our stored procs and other code that interacts with the database that is NOT using EF Core to do so).  So the inability to have EFCore generate the same C# classes and behaviors that previous EF tools supported (for instance EF6) is a problem for us.

You rejecting the OPTION of letting clients generate the code they need is very unfortunate.  Your opinion that they shouldn't want the feature, does not hold weight in whether or not the feature is useful.  If you simply google for this error message you will see no less than 5 places where other threads by different authors are seeking this feature.

**Comment by ErikEJ** [comment]
@rationalmonkey As stated above, this PR is not a valid fix, and as a maintainer I am allowed to refuse invalid fixes.

Let me think about the correct fix, based on this requirement:
**an option for all non-nullable bools to not have any defaults defined** 

@rationalmonkey I assume that would solve your issue?

In the meantime, you can try to scaffold your database with a user that does not have VIEW DEFINITION rights.

**Comment by ErikEJ** [comment]
@rationalmonkey I have re-opened #160

**Pull request closed without merging**
