### PR TITLE
Move EF Core 6 to the first item #1367

### PR DESCRIPTION
**Pull request by doggy8088**

### CODE REVIEW

**Review by ErikEJ — CHANGES_REQUESTED** [review]
That wont work. It is serialized as int.

**Comment by ErikEJ** [comment]
I think this line should set a new default: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerOptions.cs#L50

**Comment by doggy8088** [comment]
done.

**Comment by ErikEJ** [comment]
Thanks a lot!

**Pull request merged**
