### PR TITLE
Stored procedures return list

### PR DESCRIPTION
**Pull request by pedromcrocha**
Proposal

Option for stored procedures return List instead of array

image

### CODE REVIEW

**Comment by ErikEJ** [comment]
Why is that important? 
Can you just not do ToList() on the result?

**Comment by pedromcrocha** [comment]
of course, but i always use list, and ef have beautiful method that retrieve  a list (ToListAsync), why not use that.

**Comment by ErikEJ** [comment]
Thanks, maybe in future create an issue so we can discuss before submitting a PR (that may not get accepted) ?

**Comment by pedromcrocha** [comment]
you are right, next time i will have more attention.
thanks for your patience with me.

**Comment by ErikEJ** [comment]
I really appreciate your great contributions!

**Pull request merged**
