### PR TITLE
French localization added

### PR DESCRIPTION
**Pull request by omatrot**

### CODE REVIEW

**Comment by ErikEJ** [comment]
Did you miss some changes to SharedLocale?

**Comment by ErikEJ** [comment]
Thank so much!

**Comment by ErikEJ** [comment]
@omatrot You missed all the files in the root of the project!

**Comment by omatrot** [comment]
PR on its way

**Comment by ErikEJ** [comment]
Great,!!

**Comment by ErikEJ** [comment]
Tres bien!

**Pull request merged**
