### PR TITLE
ProvideBindingRedirection System.ValueTuple (#133)

### PR DESCRIPTION
**Pull request by epuig-ssinergie**

### CODE REVIEW

**Comment by ErikEJ** [comment]
Does your P build locally??

**Comment by epuig-ssinergie** [comment]
Yes it builds locally in Debug and Release "x86" config.

C:\projects\efcorepowertools\src\GUI\packages\Microsoft.VSSDK.BuildTools.15.6.170\tools\VSSDK\Microsoft.VsSDK.targets(1002,5): error : CreatePkgDef : error : ProvideBindingRedirectionAttribute: Invalid value specified for NewVersion. 

https://developercommunity.visualstudio.com/content/problem/103049/createpkgdef-error.html
https://github.com/aspnet/Razor/issues/986

this error is probably config related, but i have no idea how to check or resolve this.

**Comment by Herdo** [comment]
@ErikEJ Could you change the build definition of appveyor, please?
https://github.com/Microsoft/VSProjectSystem/issues/228#issuecomment-309175460

- Add verbose info
- Add rebuild, just to make sure there are no artifacts left behind from a previous build (I don't know exactly how appveyor works on this end)

**Comment by ErikEJ** [comment]
The proper solution is to use a newer VS version

**Pull request closed without merging**
