### PR TITLE
Add more images to table list and move them in front

### PR DESCRIPTION
**Pull request by ErikEJ**

### CODE REVIEW

**Comment by ErikEJ** [comment]
@sm15455 FYI

**Comment by sm15455** [comment]
Looks good. Maybe TableModel should be renamed to ObjectModel.

**Comment by ErikEJ** [comment]
image

**Comment by ErikEJ** [comment]
If we redesign more, we can rename classes and refactor HasPrimaryKey

**Comment by sm15455** [comment]
Ok, I'll try to do that when I'll implement object groups in treeview.

**Comment by ErikEJ** [comment]
image

**Comment by sm15455** [comment]
The good old EF6 experience... With grouping we'll be there :D

**Comment by ErikEJ** [comment]
The distinction between views and tables is more blurry with EF Core, though.

**Comment by ErikEJ** [comment]
I also think the "schema" (dbo) level is unnecessary.

**Comment by sm15455** [comment]
You are right. I would avoid nesting per schema. We can always implement it later if users ask for it. You are also right about viees and tables in EF Core, but this view organizes database objects and there the classification is clear.

**Pull request merged**
