### PR TITLE
Updated french translations.

### PR DESCRIPTION
**Pull request by jscarle**
I reviewed and updated all of the french translations while also fixing a few minor typos in the english translations.

### CODE REVIEW

**Comment by ErikEJ** [comment]
Ups, there already is a pending PR... I will compare them

**Comment by jscarle** [comment]
Yea, unfortunately I saw your tweet but didn't see the duplicate PR until I was done. 🙃

**Comment by ErikEJ** [comment]
I think I will take yours and the combine with the two additional files from the other PR

**Comment by ErikEJ** [comment]
I merged the first PR, causing a few conflicts - are you abel to have a look or would you like me to decide? :smile:

**Comment by jscarle** [comment]
Absolutely, give me a few minutes and I'll resolve them.

**Comment by jscarle** [comment]
Fixed.

**Comment by ErikEJ** [comment]
Merveilleux! Merci

**Comment by jscarle** [comment]
Avec plaisir. 😉

**Pull request merged**
