### PR TITLE
Nuget updates and removed deprecated

### PR DESCRIPTION
**Pull request by CorsairRO**
- EFCorePowerTools + Tests -  Moved to .NET 4.8
- 
- Removed Unused nuget VSSDK from EFCore and Tests

- Replaced GalaSoft MVVM deprecated nugets with Community.Mvvm (
Refactoring all ViewModels
ViewModelBase => ObservableObject
RaisePropertyChanged() => OnPropertyChanged()
Set(ref field, value ) => SetProperty
EFCoreTools - ServiceProvider -> using Mvvm.WeakMessagener instead of old Messenger
)

- Upgraded EFCorePowerTools to use Community.VisualStudio.Tookit 17

- Had to add Comvisible(true) to OptionsPageGeneral othwerwise it was not building at all, even without any of my changes

- Run all the tests

### CODE REVIEW

**Comment by ErikEJ** [comment]
Ping?

**Comment by CorsairRO** [comment]
hello,

sorry for that, i've been a bit busy these days. I will remove the nuget updates that makes it not wo work with 2019 there.

**Comment by ErikEJ** [comment]
Thanks a lot for your contribution

**Comment by ErikEJ** [comment]
@CorsairRO Did you test the update? Looks like WPF is broken. 

(OK button remains disabled)

image

**Comment by CorsairRO** [comment]
Hello @ErikEJ 

I am TOTALLY lost now with this shit git. I can see that you have closed the Pull request saying merged into master.

I checked my VS and i have NOTHING to checkin. I had yesterday an option to Push and Stash or something similar, which i did.
So i dont know what else should i do there in order for you to get my changes...

**Comment by ErikEJ** [comment]
rename ýour branch and create a new PR?

**Comment by CorsairRO** [comment]
I didnt find any way to rename any branch. I pressed the Fork button and now i get this, which sounds like my prev branch.
I have a Create pull request but it says there with red Can't Auto Merge

image

Just asking how to do it right, especially if you have it seems lots of experience with this source control, while i am still learning it. Anyway it is very complicated, much different then my current TVFC where checkin and checkout are clear and single options

**Pull request merged**
