### PR TITLE
Fix #193 not adding mysql connection through reverse engineer

### LINKED ISSUE #193: After adding the mysql connection, the option is empty
select "EF Core Power Tools" - "Reverse Engineer"  choose Database connection - Add Mysql，After adding the mysql connection, the option is empty
image
@ErikEJ

### PR DESCRIPTION
**Pull request by jespersh**
Adding a new mysql connection through reverse engineering was initially missed.

### CODE REVIEW

**Comment by jespersh** [comment]
Same provider guid yes

**Comment by ErikEJ** [comment]
And you had no issues with F5 in the latest master?

**Comment by jespersh** [comment]
> 
> 
> And you had no issues with F5 in the latest master?

F5 as in debug?
You can find me in gitter chat

**Comment by ErikEJ** [comment]
Thanks a lot!

**Pull request merged**
