### PR TITLE
Add Simplified Chinese Localization

### PR DESCRIPTION
**Pull request by Varorbc**

### CODE REVIEW

**Comment by ErikEJ** [comment]
Just a rename of existing files??

**Comment by Varorbc** [comment]
Maybe I should say that only Simplified Chinese is supported

**Comment by ErikEJ** [comment]
But is it not better to leave as is then? And drop this PR?

**Comment by Varorbc** [comment]
Simplified Chinese and traditional Chinese are still quite different and cannot be shared

**Comment by ErikEJ** [comment]
Sorry, I am an ignorant! 

Is this ready to merge?

**Comment by Varorbc** [comment]
yes

**Pull request merged**
