### PR TITLE
add comand to edit and refresh efpt.config.json files

### PR DESCRIPTION
**Pull request by pedromcrocha**
Create a context menu in the file solution explorer as efpt. * Config.json
Edit configuration
Update

I made the necessary changes to ReverseEngineerHandler
More testing is needed with Dacpac

### CODE REVIEW

**Comment by ErikEJ** [comment]
I think you forgot to use latest master :-)

**Comment by ErikEJ** [comment]
But great contribution - I really like the idea!

**Comment by pedromcrocha** [comment]
i am new with github.
but i have incorporated your last changes

**Comment by ErikEJ** [comment]
But there are merge conflicts.

Get the latest master, and the apply the changes in this PR. (Sorry, git support in writing is hard)

**Pull request closed without merging**
