### PR TITLE
I have no clue what I am doing!

### PR DESCRIPTION
**Pull request by ErikEJ**
Please help!

### CODE REVIEW

**Comment by mariohik** [comment]
Do you still need a help to test?

**Comment by ErikEJ** [comment]
@mariohik feel free to try the latest daily build

**Comment by mariohik** [comment]
I downloaded the VSIX Gallery extension and got the latest version from there. Is that right?

I can connect to the database.

image
image

After that, the server list remains empty.

image

**Comment by ErikEJ** [comment]
You need to install the Oracle VS Tools, please read the wiki post.

**Comment by mariohik** [comment]
Oracle is really a mess!
The Oracle VS Tools is already installed on VS2019 and VS2019 Preview.

image

**Comment by ErikEJ** [comment]
In the first dialog, select other, and pick the provider from the drop-down...

**Comment by mariohik** [comment]
image
image
image

**Comment by mariohik** [comment]
I'll reinstall ODT for VS2019

**Comment by ErikEJ** [comment]
Are you running the latest daily build?

**Comment by mariohik** [comment]
I'm getting it from VSIX Gallery.
Is that correct?

image

**Comment by ErikEJ** [comment]
That looks correct, guess Oracle VS Tools are broken then

**Comment by mariohik** [comment]
OK!
It took a day but finally got this working.

**1. Install ODT for VS2019**

**2. Add the connection to the Server Explorer using Oracle Database (ODP.NET, Managed Driver)**

image

image

**3. The connection will appear automatically on EF Core Power Tools**

image

**Comment by ErikEJ** [comment]
Wauw - I will clarify in the docs

**Comment by ErikEJ** [comment]
So you can confirm that reverse engineering with Oracle works for you?

**Comment by mariohik** [comment]
The DbContext was generated but the selected table was not.
I was having the same problem with Scaffold-DbContext and it only worked when I capitalized the table.

**Comment by ErikEJ** [comment]
Please report this to Oracle support

**Comment by ErikEJ** [comment]
image

**Comment by ErikEJ** [comment]
I have updated the wiki

**Comment by mariohik** [comment]
From the Oracle Forum:

> Both .NET and Oracle DB are case-sensitive. If your table name is TABLEA, then you need to use the same capitalization in .NET to identify the table.

**Comment by ErikEJ** [comment]
But I do not change the casing of table names, and the command to get the tables is implemented in the Oracle EF Core provider

**Comment by mariohik** [comment]
I upgraded to the latest version of ODP.NET (19.3.1.0) and its EFCore Power Tools (2.4.120).
Now I get the following exception:
```
System.Exception: Table list error:
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: the table or view does not exist
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution (Int32 & cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException & exceptionForArrayBindDML, BooleanDool, Boolean & StR
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader (String commandText, OracleParameterCollection paramColl, CommandType CommandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl & rdrImpl, longFetchSize Int32, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64 [] scnForExecution, Int64 [] & scnFromExecution, OracleParameterCollection & bindByPositionParamColl, Boolean & bBindParamPresent, Int64 & internalInitialLOBFS, OracleException & exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction & oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader (Boolean requiry, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader (CommandBehavior behavior)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetTablesCombined (DbConnection connection, Func`3 tableFilter, DatabaseModel databaseModel, Func`2 schemaFilter, List`1 paramList)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create (DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create (DbConnection connection, DatabaseModelFactoryOptions options)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create (String connectionString, DatabaseModelFactoryOptions options)
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions () in C: \ Code \ EFCorePowerTools \ src \ GUI \ RevEng.Core \ TableListBuilder.cs: line 39
   at efreveng.Program.Main (String [] args) in C: \ Code \ EFCorePowerTools \ src \ GUI \ efreveng \ Program.cs: line 28

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildTableResult (String output) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ EfRevEngLauncher.cs: line 156
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTablesInternal (String arguments) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ EfRevEngLauncher.cs: line 57
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetTables (String connectionString, DatabaseType databaseType) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ EfRevEngLauncher.cs: line 33
   at ReverseEngineer20.TableListBuilder.GetTableDefinitions (Boolean useEFCore5) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineer \ TableListBuilder.cs: line 30
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GetTables (String connectionString, DatabaseType databaseType, Boolean useEFCore5) in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineerHandler.cs: line 335
   at EFCorePowerTools.Handlers.ReverseEngineerHandler. <ReverseEngineerCodeFirst> d__3.MoveNext () in C: \ projects \ efcorepowertools \ src \ GUI \ EFCorePowerTools \ Handlers \ ReverseEngineerHandler.cs: line 93
```

**Comment by ErikEJ** [comment]
@mariohik  Please report an issue on this in stead of comments to this pull request!

I suggest you try the Scaffold-DbContext command with the beta 2 provider to rule out any bugs there.

**Pull request merged**
