### PR TITLE
Add UI to select column of a table

### LINKED ISSUE #596: Unable to exclude columns from model.
When I'm attempting to exclude a column using the following snippet from efpt.config.json

```json
   "Tables": [
    {
      "ExcludedColumns": [
        "AssetNumber"
      ],
      "HasPrimaryKey": true,
      "Name": "[DataLogger].[Logger]",
      "ObjectType": 0
    }
   ],
```

The excluded column is not excluded from the model. The efpt.config.json is also updated to the following (after scaffold).

```json
   "Tables": [
      {
         "Columns": [ ],
         "HasPrimaryKey": true,
         "Name": "[DataLogger].[Logger]",
         "ObjectType": 0
      }
   ],
```

### Steps to reproduce

- Add a column to the ExcludedColumns array of the table - from testing it doesn't matter what column you provide.
- Scaffold the database.

The ExcludedColumns array in efpt.json will be replaced with an empty Columns array. The requested property will still be part of the final model.

Configuration syntax is based on the release notes example https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

### Further technical details
EF Core Power Tools version: 2.5.312.0

Database engine: SQL Server

Visual Studio version: Visual Studio 16.8.0

### PR DESCRIPTION
**Pull request by sm15455**
- Changed from ListBox to TreeView for tables and column selection
- Columns of unselected tables are also unselected. When user selects a table all columns are selected. User can unselect columns. 
- Enabled UI virtualization in TreeView and tested it with 700 tables and 6000 columns. Rendering time: less than a second on my laptop. This avoids columns lazy loading in the TreeView.
- Fixes #596

### CODE REVIEW

**Comment by ErikEJ** [comment]
Can you share a screenshot or two?

**Review by ErikEJ — APPROVED** [review]

**Review by ErikEJ — CHANGES_REQUESTED** [review]
Looks good, would be nice to have a few tests included

**Comment by sm15455** [comment]
image
image

**Comment by ErikEJ** [comment]
Looks great!

**Comment by sm15455** [comment]
Glad you like it. I'll add tests and disable columns of unchecked tables. Honestly, I should also disable PrimaryKey columns but that would require another change to the models. I'll leave it for another PR :D

**Comment by sm15455** [comment]
I added some tests and made columns disabled when table is unchecked

**Comment by ErikEJ** [comment]
Don't see the tests yet...

**Comment by sm15455** [comment]
Push failed. Retried and it succeeded

**Review by ErikEJ — APPROVED** [review]

**Pull request merged**
