### PR TITLE
PR Add ReverseEnginner Edit/Refresh to folder

### PR DESCRIPTION
**Pull request by pedromcrocha**
Proposal to add ReverseEnginner Edit/Refresh to folder

### CODE REVIEW

**Comment by ErikEJ** [comment]
Could you explain / screenshot?

**Comment by pedromcrocha** [comment]
ContextMenu in folder

detect one or more config files in folder


ContexMenuInFolder

**Comment by pedromcrocha** [comment]
image

**Comment by ErikEJ** [comment]
I am unsure of the value and concerned with the complexity, and have never seen a right click action on folders in other contexts with Visual Studio...

**Comment by pedromcrocha** [comment]
it is just a shortcut, which I think will be appreciated by those who have many models/context.

if we assume that the folder or sub folder has a config file, we don’t need to search, just rigth click

**Comment by ErikEJ** [comment]
I am not sure that this adds value, and what if there are multiple files in the folder. 

Will wait for some feedback on the brand new right click option until we expand it further.

**Comment by ErikEJ** [comment]
Going to close this for now...

**Pull request closed without merging**
