### PR TITLE
Implement excluded columns

### LINKED ISSUE #572: Proposal: Specify columns to ignore during reverse engineering
Hi,

when scaffolding from database, I often need to map a property to an enum type and not to its database column type. I know I can use handlebars template, but I have another suggestion which could make life easier. Would it be possible to expand the renaming file (or create a new one) to specify columns to ignore during import? This would allow me to use partial classes to define properties for those columns and partial method in OnModelCreating to define their mapping. I know such task would not be high in the priority list, so I would be more than happy to contribute.

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes  #572

@sm15455 FYI!

### CODE REVIEW

**Comment by ErikEJ** [comment]
I have also updated release notes: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Comment by ErikEJ** [comment]
Build is stuck...

**Comment by sm15455** [comment]
Thanks for the mention in release notes, is there anything I can do about the build?

**Comment by ErikEJ** [comment]
No, AppVeyor is just busy now... Probably due to VS 16.8 issues with 100% CPU

**Comment by ErikEJ** [comment]
@sm15455 Are you on Twitter? I would like to mention this new feature in a tweet...

**Comment by sm15455** [comment]
yes, https://twitter.com/sm15455

**Pull request merged**
