### PR TITLE
Change hints page from .md to .txt #1334

### PR DESCRIPTION
**Pull request by doggy8088**

### CODE REVIEW

**Comment by ErikEJ** [comment]
The file has moved, sorry I left the old one behind. And the name is referenced from code...

**Comment by ErikEJ** [comment]
It is in the EFCorePowerTools project now.

**Review by ErikEJ — CHANGES_REQUESTED** [review]
Wrong file  sorry.

**Comment by doggy8088** [comment]
It's okay. Let me do the housekeeping. Close this PR.

**Pull request closed without merging**
