### PR TITLE
Issue Fix #60

### LINKED ISSUE #60: Feeding pluralizer before reverse engineering
Is it possible to feed the pluralizer when reverse engineering? I've got a table name called 'CourseStatus' and it's being changed to CourseStatu.

### Further technical details
EF Core Power Tools version: 1.0.604.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2017 15.7.3

### PR DESCRIPTION
**Pull request by theprateik**
Fixes #60 
In the Pluralizer class, the suffix was being extracted using the last space in the string. I have included lines to extract suffix based on the last upper case letter in the string.
Also, I commented out  {"status", "status"} from _classicalInflectionList. Because of this, "status" suffix was considered as a plural word.

### CODE REVIEW

**Comment by ErikEJ** [comment]
Thanks a lot, have a few comments, otherwise looks good

**Comment by theprateik** [comment]
@ErikEJ, I added some comments on my changes in the Pluralizer class.

**Comment by ErikEJ** [comment]
I prefer less comments and week named methods

**Comment by theprateik** [comment]
Sorry, when you said "have few comments", I read it as "have few more comments". And I went on adding comments on my changes. 
So, should I remove those comments and create a separate method or something?

**Comment by ErikEJ** [comment]
Yes, I think that makes code more readable. I just meant I had a few concrete comments to the code...

**Comment by theprateik** [comment]
@ErikEJ updated my PR

**Comment by theprateik** [comment]
Added tests for "Status" and "status"

**Pull request merged**
