### PR TITLE
Add Generation of Typescript Entities with Handlebars Templates

### PR DESCRIPTION
**Pull request by tonysneed**
Here is my first pass at adding this feature.  Couple of issues to be resolved:
- In upgrading EntityFrameworkCore.Scaffolding.Handlebars package to v2 app.config files were added with binding redirects. Is this ok or should I align dependencies?
- I added added a checkbox to EfCoreModelDialog.xaml, but we will only want to enable it when `UseHandlebars` is true. How would you like me to go about this?
- What's the best way to test the new feature?
- I got build errors on the UnitTests project complaining of missing references. (I set Debug config to x86.)

### CODE REVIEW

**Comment by ErikEJ** [comment]
What Build errors did you get? The build passed on Appveyor

**Comment by tonysneed** [comment]
Here's the build output:

```
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\DacpacTest.cs(1,27,1,30): error CS0234: The type or namespace name 'Dac' does not exist in the namespace 'Microsoft.SqlServer' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\DacpacTest.cs(3,7,3,24): error CS0246: The type or namespace name 'ReverseEngineer20' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\DgmlTest.cs(6,7,6,18): error CS0246: The type or namespace name 'DgmlBuilder' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\Services\ReplacingCandidateNamingServiceTests.cs(4,7,4,24): error CS0246: The type or namespace name 'ReverseEngineer20' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\DgmlTest.cs(14,26,14,41): error CS0246: The type or namespace name 'DebugViewParser' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\DacpacTest.cs(17,17,17,31): error CS0246: The type or namespace name 'TSqlTypedModel' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\AboutViewModelTests.cs(6,28,6,36): error CS0234: The type or namespace name 'Messages' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\AboutViewModelTests.cs(10,28,10,38): error CS0234: The type or namespace name 'ViewModels' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\PickServerDatabaseViewModelTests.cs(6,28,6,37): error CS0234: The type or namespace name 'Contracts' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\PickServerDatabaseViewModelTests.cs(9,28,9,38): error CS0234: The type or namespace name 'ViewModels' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\PickTablesViewModelTests.cs(8,28,8,37): error CS0234: The type or namespace name 'Contracts' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\PickTablesViewModelTests.cs(11,28,11,38): error CS0234: The type or namespace name 'ViewModels' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\TableInformationViewModelTests.cs(7,28,7,38): error CS0234: The type or namespace name 'ViewModels' does not exist in the namespace 'EFCorePowerTools' (are you missing an assembly reference?)
3>C:\Users\Tony\Source\EFCorePowerTools\src\GUI\UnitTests\ViewModels\PickTablesViewModelTests.cs(1316,24,1316,50): error CS0246: The type or namespace name 'ITableInformationViewModel' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 2 succeeded, 1 failed, 9 up-to-date, 0 skipped ==========
```

The source of the issue can be found in the build warnings:

```
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.ProjectSystem.VS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Shell.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.Shell.Design, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Shell.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.Shell.Design, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.ProjectSystem.VS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.CoreUtility, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.Shell.Design, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.CoreUtility, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.ProjectSystem.VS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Text.Data, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.Shell.Design, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Text.Data, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>  EFCorePowerTools -> C:\Users\Tony\Source\EFCorePowerTools\src\GUI\EFCorePowerTools\bin\x86\Debug\EFCorePowerTools.dll
2>  EFCorePowerTools -> C:\Users\Tony\Source\EFCorePowerTools\src\GUI\EFCorePowerTools\bin\x86\Debug\EFCorePowerTools.vsix
```

Looks like a version mismatch with `Microsoft.VisualStudio.ProjectSystem.VS`, `Microsoft.VisualStudio.Shell.Design`, `Microsoft.VisualStudio.Shell.Design`, `Newtonsoft.Json`.

**Comment by tonysneed** [comment]
I can still debug with the experimental instance without building UnitTests, so I'll work on the UI and manually test.

**Comment by ErikEJ** [comment]
Great! You should also remove the app.config changes and additions

**Comment by tonysneed** [comment]
All done. Enjoy!

efcpt-hbs-typescript

**Comment by ErikEJ** [comment]
Looks great - and you were able to test with F5?

**Comment by tonysneed** [comment]
Yes, F5 worked like a charm. :)

**Comment by ErikEJ** [comment]
Thanks, merged and included in latest daily build

**Comment by ErikEJ** [comment]
No updates of the CodeTemplates.zip file are required?

**Comment by tonysneed** [comment]
An update to CodeTemplates.zip is included in the PR.

**Comment by ErikEJ** [comment]
Great, I overlooked that!

**Pull request merged**
