### PR TITLE
support for CDATA without N prefix

### PR DESCRIPTION
**Pull request by m0a0k0s**

### CODE REVIEW

**Comment by ErikEJ** [comment]
Please explain what this is supposed to solve?

**Comment by m0a0k0s** [comment]
Inside a dacpac, field comments might be written in two ways and now returns next:
CDATA[N'comment'] -> comment
CDATA['comment'] -> 'comment
For a second one, I get unpaired ' that crashes my custom handling logic.

**Comment by ErikEJ** [comment]
@m0a0k0s Thanks for your contribution!

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by m0a0k0s** [comment]
It works, thank you.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Pull request merged**
