### PR TITLE
Change objects treeview virtualization mode

### PR DESCRIPTION
**Pull request by sm15455**

### CODE REVIEW

**Comment by ErikEJ** [comment]
Does this fix the renaming roundtripping issue?

**Comment by sm15455** [comment]
No, it's fixed in the other PR

**Comment by ErikEJ** [comment]
Ups, I was never notified of the other PR !?

**Comment by sm15455** [comment]
It happens, some months ago I suddenly stopped receiving emails from GitHub and After a couple of weeks I received them again

**Pull request merged**
