### PR TITLE
Add renaming capabilities to UI

### PR DESCRIPTION
**Pull request by sm15455**
It's a big one. Had to change a lot to support renaming. and schema nesting in the tree. To avoid casting to every single viewmodel in codebehind, I introduced some interface for view models. this PR introduces following features:

- Nesting schema in objects tree
- Press F2 on tables and columns to rename (it hides the textblock and shows a textbox)
- Press enter while renaming to confirm new name
- Press ESC while renaming to cancel editing
- If renamed, the table/column is shown using "NewName - (OldName)" syntax
- While selected, press space to check/unckeck the object in the treeview.
- Reads information from renaming file when shows objects treeview
- Returns information about renaming when objects treeview is closed
- Adds test

### CODE REVIEW

**Comment by ErikEJ** [comment]
Having a look now, and running the branch locally

**Comment by ErikEJ** [comment]
Fantastic! Thanks a lot

**Comment by ErikEJ** [comment]
EFPTRename

**Comment by sm15455** [comment]
Did you select all tables in the schema?

**Comment by ErikEJ** [comment]
No, a single one is unselected! :smile:

**Comment by sm15455** [comment]
Great, I was afraid UI and tests where broken :D. Just a question, how does support for multiple dbcontext work? Would It be feasible to reuse this ui for each context in a project?

**Comment by ErikEJ** [comment]
Support for multiple DbContexts in the same project is described here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time

**Comment by sm15455** [comment]
I read that. 
Does the tool regenerates all contexts each time? 
The efpt.*.config.json files don't have a UI, correct? If so, do you think it would be beneficial to provide a UI for all files? (don't know how)

**Comment by ErikEJ** [comment]
>> Does the tool regenerates all contexts each time?

No, it only operates on the selected efpt.*.config.json file (If there are multiple, a UI for picking one pops up at the start of the process)
 

>> efpt.*.config.json files don't have a UI,

Not 100% sure what you mean, but I think they do.

**Comment by sm15455** [comment]
Sorry, my fault. Didn't know a picker would show up to choose the correct file. Ignore my comments :).

**Comment by ErikEJ** [comment]
No worries, if you have any suggestions for improving that, Iet me know ( even just improving the docs)

**Comment by sm15455** [comment]
I can see two improvements:

- Improve the docs adding some screenshots and better explaining the process.
- Enable end user to create a new efpt.*.config file from UI instead of creating a new one manually and then pick one in the UI. (I don't know how honestly)

**Comment by ErikEJ** [comment]
I will create an issue to get the docs improved, and add a screenshot

**Pull request merged**
