### PR TITLE
Add Chinese translate

### PR DESCRIPTION
**Pull request by Varorbc**
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by ErikEJ** [comment]
Any ideas how I can test this? (I have only English Windows)

**Comment by Varorbc** [comment]
I've tested all the views. I can provide screenshots if necessary

**Comment by ErikEJ** [comment]
Some sample screenshots would be nice!

**Comment by Varorbc** [comment]
@ErikEJ

**Comment by sm15455** [comment]
@ErikEJ I've installed language pack from VS installer and it does its job.

**Comment by ErikEJ** [comment]
I am a bit concerned about the ability to add new features, but I guess we can just start with English

**Comment by Varorbc** [comment]
Yes.When adding new features, English is used as the default display language. If necessary, I can continue to help translate

**Comment by ErikEJ** [comment]
@Varorbc thanks, much appreciated!

**Comment by Varorbc** [comment]
Can pull requests be merged

**Comment by ErikEJ** [comment]
I see you are using just "zh" - should it not be either simplified or traditional? Or it does not matter?

**Comment by Varorbc** [comment]
I'll change to simplified Chinese later

**Comment by ErikEJ** [comment]
In a future PR?

**Comment by ErikEJ** [comment]
Thanks you very much for this!

**Comment by ErikEJ** [comment]
If you can write me a piece of chinese text or tweet the news, I would be very grateful - something like:

The latest daily build of EF Core Power Tools is now available with Chinese localization! 

(and I will include one of you screenshots)

**Comment by Varorbc** [comment]
EF Core 工具的每日版本现已支持中文本地化。

**Comment by ErikEJ** [comment]
@sm15455 could you do something similar for italian? 😁

**Pull request merged**
