### PR TITLE
Remove EDMX feature :-(

### LINKED ISSUE #939: Edmx -> Context/Model
Trying to generate context/model from EF6 edmx file. I want to do this to capture:

- Entity naming/mapping to tables & views
- Property naming/mapping to columns
- Added associations not in the database, specifically tables to views

All my attempt to achieve this fail, with the entities created using the database table/view/column names not the entity/property names in the edmx file. Also associations between views/tables defined in the edmx file are not captured.

I have also found that after selecting an edmx file and then selecting a subset of tables from the tree view does not work. entities for all tables are generated.

### Steps to reproduce

1. Select [Project]->EF Core Power Tools->Reverse Engineer
2. Clear any database connection
3. Add an edmx file. Note the edmx file is not part of the project.
4. Check Use EF Core 5
5. Click OK
6. Select all tables or a sub set
7. Click OK
8. Select Pluralize or singularize ... Note: This should not be necessary since it should take the names in the edmx file which have already been pluralized or singularized or renamed
9. Click OK

### Further technical details
EF Core Power Tools version: 2.5.612

Database engine: SQL Server/Edmx

Visual Studio version: Visual Studio 2019 16.9.4

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #939 
@omatrot  FYI :-(

### CODE REVIEW

**Comment by MagicAndre1981** [comment]
why removing instead of making it working for other providers, too?

**Comment by ErikEJ** [comment]
@MagicAndre1981 @omatrot will take ownership and I am sure he would be happy to have help moving this forward

**Comment by omatrot** [comment]
This was fun. I'm happy to move forward with what you've achieved already.

**Comment by omatrot** [comment]
@MagicAndre1981 Stay tuned for more in a new repo. Are you interested on a provider support in particular ? I won't be able to start until 2 weeks.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 Are you interested on a provider support in particular ? 

I use firebird. But DDEX is complicated to setup. I now created a VSIX for my usage, but it looks like DDEX support will be removed at all from firebird provider 😢

**Pull request merged**
